### ISSUE TITLE
Errors when running example

### ISSUE THREAD

**Issue by GuillaumeH-GR** [BioinfoMachineLearning/MULTICOM_qa#4]
Hello, 

I have tried to run MULTICOM_qa with the H1143 example but I got several errors starting by the CMAPS : 

```
Pairwise Similarity Scoring Done
Mapping chains to clusters
Mapping of chains to clusters has been done
Finding the valid dimer combinations
Completed looking for the valid dimers
Generating the CMAPS of the models
Concluded generating the CMAPS of the models
generating the CMAPS using the interchain contact predictors
expected_cmaps ./examples/H1143/output/predicted_cmaps/sequence_0_A:sequence_1_A.cmap has not been found 
```

And indeed, at the end of the run, the predicted_cmaps repertory only contains an empty extras folder. 

I also got a conda environment error (`Not a conda environment: /mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/external_tool/ZComplexMSA/env`) and a bunch of related errors. I tried to solve them by creating this environment with python 3.6 and biopython 1.79 but I got another bunch of errors.

Here is my complete console output from my last run of the example : 

```
python multi_eva.py ./examples/H1143/H1143.fasta ./examples/H1143/decoys/ A1B1 ./examples/H1143/H1143_alphafold_monomer/ 4 ./examples/H1143/output/
/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/MMalign
/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/run_CDFold.sh
./examples/H1143/H1143.fasta Found
./examples/H1143/decoys/ Found
stoichiometry A1B1
./examples/H1143/H1143_alphafold_monomer/ Found
cp ./examples/H1143/H1143_alphafold_monomer/H1143_B.pdb ./examples/H1143/output/predicted_monomer//sequence_1_A.pdb
cp ./examples/H1143/H1143_alphafold_monomer/H1143_B.pdb ./examples/H1143/output/predicted_monomer//sequence_1_B.pdb
cp ./examples/H1143/H1143_alphafold_monomer/H1143_A.pdb ./examples/H1143/output/predicted_monomer//sequence_0_A.pdb
cp ./examples/H1143/H1143_alphafold_monomer/H1143_A.pdb ./examples/H1143/output/predicted_monomer//sequence_0_B.pdb
number of pdb is 6
 Started separating of Chains
 Ended separating of Chains
Pairwise Similarity Scoring started
0.660888
0.689144
0.6762699999999999
0.602352
0.6085679999999999
0.6562459999999999
Pairwise Similarity Scoring Done
Mapping chains to clusters
Mapping of chains to clusters has been done
Finding the valid dimer combinations
Completed looking for the valid dimers
Generating the CMAPS of the models
Concluded generating the CMAPS of the models
generating the CMAPS using the interchain contact predictors
expected_cmaps ./examples/H1143/output/predicted_cmaps/sequence_0_A:sequence_1_A.cmap has not been found 

predicting the interactions 

Traceback (most recent call last):
  File "lib/pdb_process.py", line 156, in <module>
    fhandle = open(pdb_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/examples/H1143/output/predicted_monomer/sequence_0_A.pdb'
Traceback (most recent call last):
  File "lib/pdb_process.py", line 156, in <module>
    fhandle = open(pdb_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/examples/H1143/output/predicted_monomer/sequence_1_A.pdb'
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/external_tool/ZComplexMSA/run_zcomplexmsa.py", line 3, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
### Activet the virtual environment
### Runing CDPred
Traceback (most recent call last):
  File "lib/Model_predict.py", line 11, in <module>
    from generate_feature import *
  File "/mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/lib/generate_feature.py", line 104
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
The prediction map at: ./examples/H1143/output/predicted_cmaps/extras//sequence_0_A_sequence_1_A/predmap/
### Runing GDFold
Contrain file not exit!
256
sh /mnt/beegfs/userdata/g_hollaender/CondaEnv/MULTICOMqa/CDPred/run_CDFold.sh -n sequence_0_A_sequence_1_A -p './examples/H1143/output/predicted_monomer/sequence_0_A.pdb ./examples/H1143/output/predicted_monomer/sequence_1_A.pdb' -m heterodimer -o ./examples/H1143/output/predicted_cmaps/extras/sequence_0_A_sequence_1_A
./examples/H1143/output/predicted_cmaps/extras/sequence_0_A_sequence_1_A/predmap/sequence_0_A_sequence_1_A.htxt
Concluded generating the CMAPS using the interchain contact predictors
Started ICPS 
H1143TS035_4
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
H1143TS035_5
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
H1143TS035_3
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
H1143TS493_2
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
H1143TS037_3
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
H1143TS399_4
./examples/H1143/output/struct_dimer_cmaps/sequence_01/
Completed ICPS
[]
H1143TS035_4
[]
H1143TS035_4
[]
H1143TS035_5
[]
H1143TS035_5
[]
H1143TS035_3
[]
H1143TS035_3
[]
H1143TS493_2
[]
H1143TS493_2
[]
H1143TS037_3
[]
H1143TS037_3
[]
H1143TS399_4
[]
H1143TS399_4
Generating Final scoring part
 TOTAL TIME 34.67125899344683
```

I attached to this issue the output csv file I got which is clearly different from the expected one.

Can you help me resolving these errors please ?
Sorry if some of them are obvious, I'm not a bioinformatician by training.

Thank you for you consideration,

Guillaume H

[H1143.csv](https://github.com/BioinfoMachineLearning/MULTICOM_qa/files/11980701/H1143.csv)

**Comment by RajShekhorRoy** [comment]
Hi,

The problem has been caused because the program could not find predicted monomer.
I have the following suggestion:

1.  Please check the monomer input again as the error suggests it could not find the monomers.
2.  Also, try it with full path of the inputs and see if it is working. 
3.  Also, tqdm is not present in your environment, did you setup the CDpred correctly?

Regards,
Raj
